### ISSUE TITLE
Errors occur when 3 gmsl cameras are used

### ISSUE THREAD

**Issue by kooweat** [DavidTorresOcana/ros_gmsl_driver#2]
Hi,
First of all, thank you for your contribution.
I'm trying to use 3 gmsl cameras and the process keep dies when we run roslaunch.
We successfully ran roslaunch using 2 gmsl cameras.
We just changed the selector-mask parameters of successful launch file but 
the error keeps occur with the error message as,
[gmsl_n_cameras_node-1] process has died [pid 3262, exit code -11, cmd /home/nvidia/catkin_ws/devel/lib/gmsl_n_cameras/gmsl_n_cameras_node --selector-mask=00010011 --type-ab=ar0231-rccb-ss3322 __name:=gmsl_n_cameras_node __log:=/home/nvidia/.ros/log/b871b7a6-6d97-11e9-baee-00044b70725f/gmsl_n_cameras_node-1.log].
log file: /home/nvidia/.ros/log/b871b7a6-6d97-11e9-baee-00044b70725f/gmsl_n_cameras_node-1*.log

Our launch file is modified as below,
  1 <launch>
  2         
 12         # Arguments
 13         <arg name="selector-mask" value="00010011" /> # This allows you to connect any camera at any port.
 14                                                                                                 # In reversed order by port. E.g. the mask corresponds to the order [cam3,cam2,cam1,cam0] of every port.    
 15                                                                                                 # E.g. if you connect 2 cameras on port AB on slots 0 and 1 and; 2 cameras on port CD on slots 0 and 1.     Mask would be: 00110011
 16                                                                                                 # E.g. if you connect 3 cameras on port AB on slots 0,1 and 2;  1 camera on port CD on slots 0. Mask wou    ld be: 01110001
 17                                                                                                 # E.g. you should NOT connect 3 cameras on port AB on slots 1,2 and 3, because you are skipping slot 0.
 18                                                                                                 #         ALWAYS connect cameras in order 0,1,2.... in every port. This driver assumes cameras are conne    cted in order.
 19         # Nodes
 20         <node name="gmsl_n_cameras_node" pkg="gmsl_n_cameras" type="gmsl_n_cameras_node"  output="screen" args="--selector-mask=$(arg selector-mask) --type-ab=ar0231-rccb-ss3322">
 21                 # Parameters
 22                 <param name="img_compressed" type="bool" value="false" />
 23                 <param name="JPEG_quality" type="int" value="65" />
 24 
 25                 <param name="img_raw" type="bool" value="false" /> # Select img_raw OR img_raw_downsample. Not recommended to do both at same time
 26 
 27                 <param name="img_raw_downsample" type="bool" value="true" /> # Downsample the raw image and publish. It is not recommended to publish raw and raw_donwsample at same time
 28                 <param name="img_downsample_width" type="int" value="800" /> # width of the donwsample. Tune this to get the size you need
 29                 <param name="img_downsample_height" type="int" value="503" /> # height of the donwsample. Tune this to get the size you need
 30 
 31                 <param name="FPS" type="int" value="30" />
 32                 # Parameters for camera calibration: Necessary if you need to rectify
 33                 <param name="do_rectify" type="bool" value="true" /> # This does not mean the driver rectifies the images, but publishes the appropriate flag into /camera_info so image_proc does
 34                                                                                                                           #   To rectify images, use cameras_rectifier.launch (in other computer in the     network) or gmsl_n_cameras_rectifier.launch in PX2
 35                 <rosparam param="camera_type_names" subst_value="True">"onetwenty,sixty"</rosparam> # How to set camera_type_names?
 36                 
 46         </node>
 47 
 48 
 49 
 50 </launch>

Thanks in advance

**Comment by DavidTorresOcana** [comment]
Hello

It is really difficult to know what is causing the problem was that this
information.
The most typical errors are not including enough information to launch all
the cameras.
Please attach the entire .launch file to better help you.

Have you set the 3 camera types?
Have you set the 3 camera Frames?
Are you conecting correctly the cameras?
Please read all parameters of the launch file and understand what they do

Regards

**Comment by DavidTorresOcana** [comment]
Hello

Any updates on this?
Did you manage to solve the problem?
Please share your experience here for others to learn about it

Regards

**Comment by kooweat** [comment]
Sorry for late reply,
I've solved this problem by  specifying types for all camera groups.
I only specified camera types for port ab like below,
type-ab=ar0231-rccb-ss3322
