### ISSUE TITLE
camera_calibration_fisheye in camera_calibration.sh

### ISSUE THREAD

**Issue by jokla** [DavidTorresOcana/ros_gmsl_driver#4]
Hi,

I was taking a look at the file camera_calibration.sh. In this script the ros node called camera_calibration_fisheye is called. Is this part of the official camera calibration node? I didn't find it.

Thanks!

**Comment by DavidTorresOcana** [comment]
Hello

Fisheye calibration is done with this: [image_pipeline](https://github.com/DavidTorresOcana/image_pipeline/tree/indigo/camera_calibration_fisheye)
It is a fork of the official image_pipeline. With that you should be able to calibrate fisheye mono and stereo cameras.

Regards

**Comment by jokla** [comment]
Thank you @DavidTorresOcana !
