### ISSUE TITLE
Problems building the project

### ISSUE THREAD

**Issue by frobinet** [DavidTorresOcana/ros_gmsl_driver#5]
I would like to know more about building the project.

Are you building the node directly on PX2, or using the host machine? During my searches, I've seen that Driveworks cannot be compiled directly on the PX2, so I'm assuming you're cross-compiling everything on the host machine, using the cross-compilation toolchains. 

I'm not a cross-compilation expert, but I'm assuming the host needs OpenCV4Cuda and ROS in their ARM64 versions in order to be able to link everything into a single ARM64 PX2-compatible binary. Do you have any pointers on how to install such dependencies on the host? I found some information for OpenCV, but nothing working for ROS. Am I supposed to compile ROS from scratch using the cross-compilation V4L toolchain? 

Also, are any of these dependencies needed at runtime, or can I just transfer the binary to the PX2 and simply run it there without the dependencies?

Thanks for the help!

**Comment by DavidTorresOcana** [comment]
You need to cross-compile the standard SW like Driveworks and flash it into the board.

While it would be ideal to cross-compile other libraries I cannot help you on how to do that, but I encourage you to share here how to do s for other's benefit.

You can simply compile [OpenCV for Tegra ](https://docs.opencv.org/master/d6/d15/tutorial_building_tegra_cuda.html) and ROS directly in the board.
I guess you can remove all the code after compilation and leave only binaries.

**Comment by frobinet** [comment]
Thanks for your answer. Could you provide additional information about cross-compilation on the host machine? I know how to cross-compile the driveworks samples but they are not using external libraries like OpenCV or ROS. Do I have to install the ARM64 versions of OpenCV and ROS on my host machine?

**Comment by DavidTorresOcana** [comment]
You have to install Nvidia Driveworks with [Nvidia Drive's installer](https://developer.nvidia.com/drive/downloads). That will cross-compile Driveworks for you.

You can install OpenCV and ROS arm versions on DrivePX directly, no cross-compilation.

**Comment by frobinet** [comment]
Alright I got it. For some reason I was sure that I had to compile the node on the host, but transferring the Driveworks binaries worked just fine. 

If I find a way to do make the whole thing without touching the PX2, I will make a documentation PR.

Thanks for your help!

**Comment by DavidTorresOcana** [comment]
> Alright I got it. For some reason I was sure that I had to compile the node on the host, but transferring the Driveworks binaries worked just fine.
> 
> If I find a way to do make the whole thing without touching the PX2, I will make a documentation PR.
> 
> Thanks for your help!

Perfect. That would be fantastic!
